### ISSUE TITLE
viewer width and height

### ISSUE THREAD

**Issue by sarjuxtn** [Accusoft/ACS-Viewer-PHP-Library#1]
The configuration :
  'viewerWidth' => '50%',
  'viewerHeight' => '50%'
is not working.

here is my configuration:
$viewer = new ACSViewer(array(
  'key' => 'K2092014193734',
  'document' => 'http://images.accusoft.com/documents/prizm-cloud_slides.pdf',
  'toolbarColor' => '000000',
  //'printButton' => 'yes',
  'viewerWidth' => '50%',
  'viewerHeight' => '50%'
));

**Comment by eibbini** [comment]
Please Change viewerWidth & viewerHeight to be all lowercase. Please make sure you get the latest code of ACSViewer.php as there are some modifications for the optional parameters to be passed to our ACS Viewer.

viewerwidth' => '50%',
'viewerheight' => '50%'

**Comment by sarjuxtn** [comment]
Thanks :)
