### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by sarjuxtn** [Accusoft/ACS-Viewer-PHP-Library#2]
Hello eibbini,
The api key generated is not working, i can see a regular expression for this key in the code.
:'key' => '#^K\d+$#',
It starts with K and contains digits. Whereas the key generated contains alphanumeric characters.
I am kinda lost. Can you help me here.

Thanks.

**Comment by zehreen** [comment]
Hello 

I am getting the same problem here. Can you please check it ?

**Comment by eibbini** [comment]
You are absolutely right. This is an old regular expression , is only valid for what we call ACS Legacy keys. anyway, I modified the expression to accept any key with at least 8 characters " 'key' => '/^\S{8,}\z/' ". Please make sure you sign up to Accusoft Cloud Services to get your api key.
  
https://www.accusoft.com/products/accusoft-cloud-services/portal/

**Comment by zehreen** [comment]
Thanks eibbini :)
